version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      - MYSQL_ROOT_PASSWORD=57585900
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=57585900
      - MYSQL_DATABASE=ngxproxy
      - MYSQL_USER=ngxproxy
      - MYSQL_PASSWORD=255025

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:6.0-ubuntu-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=57585900
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:6.0-ubuntu-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    volumes:
     - '/etc/httpd/ssl/:/etc/ssl/apache2'
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=57585900
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER=zabbix-server
      - ZBX_SERVER_NAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - mysql
      - zabbix-server
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest-ubuntu
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app 4.2.9
    depends_on:
      - mysql
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:6.0-ubuntu-latest
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_NAME=zabbix-server
      - Server=zabbix-server
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    networks:
      - network-zabbix
    ports:
      - '90:80'
      - '81:81'
      - '450:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./nginx/data:/data/ngxproxy
      - ./nginx/data/letsencrypt:/etc/letsencrypt
  db:
    image: 'yobasystems/alpine-mariadb'
    networks:
      - network-zabbix
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./nginx/mysql:/var/lib/mysql